#!/usr/bin/python

import MySQLdb as mdb
db = mdb.connect('localhost', 'statsW', 'zeb', 'repo')
cur = db.cursor()

lines = open('./authorsUCB.txt')
authors = []
with db:
    for line in lines:
        chunks = line.strip().split()
        cur.execute("INSERT INTO authors (lname, fname, institution) VALUES (%s,%s,%s)", (chunks[1], chunks[0], 'Berkeley Law'))

db.close()